language: python

# command to install dependencies
install:
  - pip install -r utilities/requirements.txt

# command to run tests
script: coverage run --source=searchEngine, manage.py test


# command to gauge test coverage AFTER success
after_script: coverage report -m 

# notify the squad
notifications:
  email:
    recipients:
      - tse.developers@gmail.com
    on_success: always
    on_failure: always