language: python

notifications:
  email:
    - tse.developers@gmail.com

# command to install dependencies
install:
  - pip install django==1.6.5
# command to run tests
script: python manage.py test
